id: P002964
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:31:21.995403
source_metadata:
  id: bdr:W30345
  title: གྲོ་ལོད་རྒྱབ་ཆོས་ཕྱོགས་སྒྲིགས
  author: ''
  volumes:
    056fc3df905c4d3188c700ec5a7aad0f:
      image_group_id: I6116
      title: ''
      volume_number: 1
      total_pages: 624
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
